name: ticketportal
favicon: null
layout_spectrum: 0.924773613223806
typography_spectrum: 0.2710537831299007
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.005941700655966997
  lightness: 0.5380565079394728
  saturation: 0.8883403388317674
  rhythmicContrast: 0.7170575640629977
purpose: []
